### ISSUE TITLE
Null field major_tick_start on certain designs

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#497]
I found two files that have this problem:

__4_helix_grid_none_min_offset_position_x_nondefault.sc__:
```
I encountered an error while reading the file 4_helix_grid_none_min_offset_position_x_nondefault.sc:

****************************************************************************************************
* error type:    BuiltValueNullFieldError
* error message: Tried to construct class "Helix" with null field "major_tick_start". This is forbidden; to allow it, mark "major_tick_start" with @nullable.
****************************************************************************************************

That file's contents are printed below.

**********************************************************************************
* If you believe this is due to a bug in scadnano, please file a bug report at   *
*   https://github.com/UC-Davis-molecular-computing/scadnano/issues              *
* Include this entire message in the email.                                      *
**********************************************************************************

stack trace:
Tried to construct class "Helix" with null field "major_tick_start". This is forbidden; to allow it, mark "major_tick_start" with @nullable.
    at Object.wrapException (https://scadnano.org/main.dart.js:1181:17)
    at Object.throwExpression (https://scadnano.org/main.dart.js:1195:15)
    at HelixBuilder.build$0 (https://scadnano.org/main.dart.js:89771:15)
    at Object.Design_from_json (https://scadnano.org/main.dart.js:34365:79)
    at Object.load_dna_file_reducer (https://scadnano.org/main.dart.js:21491:40)
    at StaticClosure.app_state_reducer (https://scadnano.org/main.dart.js:28205:18)
    at Store__createReduceAndNotify_closure.call$1 (https://scadnano.org/main.dart.js:62505:28)
    at StaticClosure.periodic_design_save_local_storage_middleware (https://scadnano.org/main.dart.js:35199:55)
    at Store__createDispatchers_closure.call$1 (https://scadnano.org/main.dart.js:62515:34)
    at StaticClosure.edit_select_mode_change_middleware (https://scadnano.org/main.dart.js:10971:55)

The file 4_helix_grid_none_min_offset_position_x_nondefault.sc has this content:

{
  "version": "0.11.0",
  "grid": "none",
  "helices": [
    {
      "position": {"x": 0, "y": 0, "z": 0},
      "major_tick_distance": 4
    },
    {
      "min_offset": 8,
      "position": {"x": 0, "y": 3, "z": 3},
      "major_tick_distance": 4
    },
    {
      "position": {"x": 2.5, "y": -3, "z": 8},
      "major_tick_distance": 4
    },
    {
      "min_offset": 8,
      "position": {"x": 2.5, "y": 1, "z": 11},
      "major_tick_distance": 4
    }
  ],
  "strands": [
    {
      "color": "#f74308",
      "domains": [
        {"helix": 0, "forward": true, "start": 0, "end": 16}
      ]
    },
    {
      "color": "#57bb00",
      "domains": [
        {"helix": 1, "forward": true, "start": 8, "end": 16}
      ]
    },
    {
      "color": "#888888",
      "domains": [
        {"helix": 2, "forward": true, "start": 0, "end": 16}
      ]
    },
    {
      "color": "#32b86c",
      "domains": [
        {"helix": 3, "forward": true, "start": 8, "end": 16}
      ]
    }
  ]
}
```

__4_helix_min_offsets_nonzero.sc__:
```
I encountered an error while reading the file 4_helix_min_offsets_nonzero.sc:

****************************************************************************************************
* error type:    BuiltValueNullFieldError
* error message: Tried to construct class "Helix" with null field "major_tick_start". This is forbidden; to allow it, mark "major_tick_start" with @nullable.
****************************************************************************************************

That file's contents are printed below.

**********************************************************************************
* If you believe this is due to a bug in scadnano, please file a bug report at   *
*   https://github.com/UC-Davis-molecular-computing/scadnano/issues              *
* Include this entire message in the email.                                      *
**********************************************************************************

stack trace:
Tried to construct class "Helix" with null field "major_tick_start". This is forbidden; to allow it, mark "major_tick_start" with @nullable.
    at Object.wrapException (https://scadnano.org/main.dart.js:1181:17)
    at Object.throwExpression (https://scadnano.org/main.dart.js:1195:15)
    at HelixBuilder.build$0 (https://scadnano.org/main.dart.js:89771:15)
    at Object.Design_from_json (https://scadnano.org/main.dart.js:34365:79)
    at Object.load_dna_file_reducer (https://scadnano.org/main.dart.js:21491:40)
    at StaticClosure.app_state_reducer (https://scadnano.org/main.dart.js:28205:18)
    at Store__createReduceAndNotify_closure.call$1 (https://scadnano.org/main.dart.js:62505:28)
    at StaticClosure.periodic_design_save_local_storage_middleware (https://scadnano.org/main.dart.js:35199:55)
    at Store__createDispatchers_closure.call$1 (https://scadnano.org/main.dart.js:62515:34)
    at StaticClosure.edit_select_mode_change_middleware (https://scadnano.org/main.dart.js:10971:55)

The file 4_helix_min_offsets_nonzero.sc has this content:

{
  "version": "0.11.0",
  "grid": "square",
  "helices": [
    {"max_offset": 30, "grid_position": [0, 0]},
    {"min_offset": 1, "max_offset": 30, "grid_position": [0, 1]},
    {"min_offset": 2, "max_offset": 30, "grid_position": [0, 2]},
    {"min_offset": 3, "max_offset": 30, "grid_position": [0, 3]}
  ],
  "strands": [
    {
      "color": "#f74308",
      "domains": [
        {"helix": 0, "forward": true, "start": 0, "end": 29}
      ]
    },
    {
      "color": "#0066cc",
      "domains": [
        {"helix": 0, "forward": false, "start": 0, "end": 29}
      ]
    }
  ]
}
```

**Comment by UnHumbleBen** [comment]
The issue seems to lie here:

https://github.com/UC-Davis-molecular-computing/scadnano/blob/36d27dd00b048fb63105951b4afad5c4a4e491a1/lib/src/state/design.dart#L1586-L1613

If min_offset is non-null, then major_tick_start might not be set.

I think the fix should be to pull out that last if statement:

```dart
set_helices_min_max_offsets(Map<int, HelixBuilder> helix_builders, Iterable<Strand> strands) {
  var helix_idx_to_substrands = construct_helix_idx_to_domains_map(strands, helix_builders.keys);


  for (int idx in helix_builders.keys) {
    HelixBuilder helix_builder = helix_builders[idx];


    if (helix_builder.max_offset == null) {
      helix_builder.max_offset = calculate_default_max_offset(strands);
    }


    if (helix_builder.min_offset == null) {
      var substrands = helix_idx_to_substrands[helix_builder.idx];
      var min_offset = substrands.isEmpty ? constants.default_min_offset : substrands.first.start;
      for (var substrand in substrands) {
        min_offset = min(min_offset, substrand.start);
      }
      // if there are strands with no offsets less than 1, we still want Helix.min_offset to be 0
      // i.e., it can only be positive if the JSON explicitly declares that
      if (min_offset > 0) {
        min_offset = 0;
      }
      helix_builder.min_offset = min_offset;
      // used to be here
    }
    // Move this out to here
    if (helix_builder.major_tick_start == null) {
      helix_builder.major_tick_start = min_offset;
    }
  }
}
```

This way, major_tick_start is set even if min_offset is non-null

**Comment by UnHumbleBen** [comment]
Fixed in https://github.com/UC-Davis-molecular-computing/scadnano/pull/499
