### ISSUE TITLE
Fix Assertion Failed Error When Attempting to Move Group

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#696]
This issue is appearing on dev but not main:

Steps to reproduce:
1. Open up any design.
2. Switch to Move Group Edit Mode (press m).
3. Try to move a group (ctrl + click + drag).

This error pops up:

```
Assertion failed: "boolean expression must not be null"

stack trace:
Assertion failed: "boolean expression must not be null"
    at Object.wrapException (https://scadnano.org/dev/main.dart.js:1181:17)
    at Object.assertThrow (https://scadnano.org/dev/main.dart.js:1669:15)
    at Object.boolConversionCheck (https://scadnano.org/dev/main.dart.js:1665:11)
    at _$DesignMainHelixComponent.render$0 (https://scadnano.org/dev/main.dart.js:114978:60)
    at ReactDartInteropStatics2_handleRender_closure.call$0 (https://scadnano.org/dev/main.dart.js:67838:17)
    at _RootZone.run$1$1 (https://scadnano.org/dev/main.dart.js:46467:18)
    at StaticClosure.ReactDartInteropStatics2_handleRender (https://scadnano.org/dev/main.dart.js:15258:28)
    at Object.Primitives_applyFunction (https://scadnano.org/dev/main.dart.js:1064:30)
    at Object.Function_apply (https://scadnano.org/dev/main.dart.js:6108:16)
    at _callDartFunctionFast (https://scadnano.org/dev/main.dart.js:8476:16)
```

**Comment by dave-doty** [comment]
Here's the more useful stack trace giving Dart line numbers from running locally:

```
Failed assertion: boolean expression must not be null

stack trace:
dart:sdk_internal 5140:32                                             test
package:scadnano/src/view/design_main_helix.dart 65:51                <fn>
package:scadnano/src/view/design_main_helix.dart 71:19                <fn>
package:scadnano/src/view/design_main_helix.dart 121:17               render
package:react/src/react_client/dart_interop_statics.dart 314:25       <fn>
dart:sdk_internal 35607:58                                            run
package:react/src/react_client/dart_interop_statics.dart 311:21       handleRender
dart:sdk_internal 57948:21                                            ret
package:react/react.js 317:41                                         render
package:react/react_dom.js 5342:100                                   finishClassComponent
package:react/react_dom.js 5334:202                                   updateClassComponent
package:react/react_dom.js 5643:890                                   beginWork
package:react/react_dom.js 3195:119                                   callCallback
package:react/react_dom.js 3215:45                                    invokeGuardedCallbackDev
package:react/react_dom.js 3234:126                                   invokeGuardedCallback
package:react/react_dom.js 6574:1                                     beginWork$1
package:react/react_dom.js 6363:150                                   performUnitOfWork
package:react/react_dom.js 6356:30                                    workLoopSync
package:react/react_dom.js 6353:195                                   renderRootSync
package:react/react_dom.js 6283:121                                   performSyncWorkOnRoot
package:react/react_dom.js 4607:188                                   <fn>
package:react/react_dom.js 10833:16                                   unstable_runWithPriority
package:react/react_dom.js 4601:1059                                  runWithPriority$1
package:react/react_dom.js 4607:78                                    flushSyncCallbackQueueImpl
package:react/react_dom.js 4606:339                                   flushSyncCallbackQueue
package:react/react_dom.js 6306:20                                    batchedUpdates$1
package:react/react_dom.js 8442:7                                     notify
package:react/react_dom.js 8513:20                                    notifyNestedSubs
package:react/react_dom.js 8518:12                                    handleChangeWrapper
dart:sdk_internal 5065:17                                             dcall
package:over_react/src/over_react_redux/over_react_redux.dart 510:55  <fn>
dart:sdk_internal 31412:9                                             <fn>
```

**Comment by dave-doty** [comment]
Seems like the issue is this line that was added to handle issue #

```dart
..className = 'main-view-helix-circle ' + (props.selected ? "selected" : "")
```

I imagine the problem is that the React Prop `props.selected` is not being set to `true` or `false` in all circumstances, so it defaults to `null`.
