### ISSUE TITLE
click-dragging Extension ends crashes

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#845]
On both the dev and main sites (but not when I run locally from the dev branch, though I do get a React key error, see below comment), click-dragging an end on an extension causes a crash:

![image](https://user-images.githubusercontent.com/19274365/222123201-0eaacef2-d54c-4dd4-b20b-e4936e76fb41.png)

Drag the middle end somewhere. I get this error:

```
Uncaught Error: Objects are not valid as a React child (found: object with keys {_source, _f, $ti}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react_dom.js:4792:827)
    at reconcileChildFibers (react_dom.js:4931:713)
    at reconcileChildren (react_dom.js:5239:22)
    at finishClassComponent (react_dom.js:5347:88)
    at updateClassComponent (react_dom.js:5334:202)
    at beginWork (react_dom.js:5643:890)
    at HTMLUnknownElement.callCallback (react_dom.js:3195:119)
    at Object.invokeGuardedCallbackDev (react_dom.js:3215:45)
    at invokeGuardedCallback (react_dom.js:3234:126)
    at beginWork$1 (react_dom.js:6574:1)
react_dom.js:5846 The above error occurred in the <PotentialExtensionsView> component:

    at ReactDartComponent2 (https://scadnano.org/packages/react/react.js:275:7)
    at ConnectFunction (https://scadnano.org/packages/react/react_dom.js:7433:75)
    at g
    at ReactDartComponent2 (https://scadnano.org/packages/react/react.js:275:7)
    at ConnectFunction (https://scadnano.org/packages/react/react_dom.js:7433:75)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at ReactDartComponent2 (https://scadnano.org/packages/react/react.js:275:7)
    at ReactDartComponent2 (https://scadnano.org/packages/react/react.js:275:7)

React will try to recreate this component tree from scratch using the error boundary you provided, RecoverableErrorBoundary.
logCapturedError @ react_dom.js:5846
react_dom.js:4792 Uncaught Error: Objects are not valid as a React child (found: object with keys {_source, _f, $ti}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react_dom.js:4792:827)
    at reconcileChildFibers (react_dom.js:4931:713)
    at reconcileChildren (react_dom.js:5234:22)
    at finishClassComponent (react_dom.js:5347:88)
    at updateClassComponent (react_dom.js:5334:202)
    at beginWork (react_dom.js:5643:890)
    at HTMLUnknownElement.callCallback (react_dom.js:3195:119)
    at Object.invokeGuardedCallbackDev (react_dom.js:3215:45)
    at invokeGuardedCallback (react_dom.js:3234:126)
    at beginWork$1 (react_dom.js:6574:1)
react_dom.js:5846 The above error occurred in the <PotentialExtensionsView> component:

    at ReactDartComponent2 (https://scadnano.org/packages/react/react.js:275:7)
    at ConnectFunction (https://scadnano.org/packages/react/react_dom.js:7433:75)
    at g
    at ReactDartComponent2 (https://scadnano.org/packages/react/react.js:275:7)
    at ConnectFunction (https://scadnano.org/packages/react/react_dom.js:7433:75)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at Provider (https://scadnano.org/packages/react/react_dom.js:7146:20)
    at ReactDartComponent2 (https://scadnano.org/packages/react/react.js:275:7)
    at ReactDartComponent2 (https://scadnano.org/packages/react/react.js:275:7)

React will try to recreate this component tree from scratch using the error boundary you provided, DesignMainErrorBoundary.
logCapturedError @ react_dom.js:5846
react_dom.js:5846 The above error occurred in the <DesignMainErrorBoundary> component:

    at ReactDartComponent2 (https://scadnano.org/packages/react/react.js:275:7)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react_dom.js:5846
main.dart.js:48757 Uncaught TypeError: error.get$stackTrace is not a function
    at _$DesignMainErrorBoundaryComponent.render$0 (main.dart.js:123120:284)
    at ReactDartInteropStatics2_handleRender_closure.call$0 (main.dart.js:70913:17)
    at _RootZone.run$1$1 (main.dart.js:48822:18)
    at StaticClosure.ReactDartInteropStatics2_handleRender (main.dart.js:16244:28)
    at Object.Primitives_applyFunction (main.dart.js:1143:30)
    at Object.Function_apply (main.dart.js:6220:16)
    at _callDartFunctionFast (main.dart.js:8562:16)
    at Object.handleRender (main.dart.js:8553:18)
    at ReactDartComponent2.render (react.js:317:41)
    at finishClassComponent (react_dom.js:5342:100)
```

**Comment by dave-doty** [comment]
Might be unrelated, but when I run locally from the dev branch there is a React key error (but that doesn't erase the design like the above error):

```
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at _$36PotentialExtensionsViewComponent (http://localhost:8080/packages/react/react.js:275:7)
    at ConnectFunction (http://localhost:8080/packages/react/react_dom.js:7433:75)
    at g
    at _$36DesignMainComponent (http://localhost:8080/packages/react/react.js:275:7)
    at ConnectFunction (http://localhost:8080/packages/react/react_dom.js:7433:75)
    at Provider (http://localhost:8080/packages/react/react_dom.js:7146:20)
    at Provider (http://localhost:8080/packages/react/react_dom.js:7146:20)
    at Provider (http://localhost:8080/packages/react/react_dom.js:7146:20)
    at Provider (http://localhost:8080/packages/react/react_dom.js:7146:20)
    at Provider (http://localhost:8080/packages/react/react_dom.js:7146:20)
    at Provider (http://localhost:8080/packages/react/react_dom.js:7146:20)
    at Provider (http://localhost:8080/packages/react/react_dom.js:7146:20)
    at _$36RecoverableErrorBoundaryComponent (http://localhost:8080/packages/react/react.js:275:7)
    at _$36DesignMainErrorBoundaryComponent (http://localhost:8080/packages/react/react.js:275:7)
```
