### ISSUE TITLE
Give more useful error message when `.sc` file format is incorrect

### ISSUE THREAD

**Issue by LSDaniel2016** [UC-Davis-molecular-computing/scadnano#849]
I encountered an error while reading the file Origami-hinge-ok.json:
but CadnanoSQ can open it which I received from my collegue.
![image](https://user-images.githubusercontent.com/36099907/224690962-0c125510-ed27-40fa-a8e4-f2c54ee70e67.png)

****************************************************************************************************
* error type:    NullError
* error message: NoSuchMethodError: method not found: 'get$iterator' on null
****************************************************************************************************

That file's contents are printed below.

**********************************************************************************
* If you believe this is due to a bug in scadnano, please file a bug report at   *
*   https://github.com/UC-Davis-molecular-computing/scadnano/issues              *
* Include this entire message in the email.                                      *
**********************************************************************************

stack trace:
TypeError: Cannot read properties of null (reading 'get$iterator')
    at Object.get$iterator$ax (https://scadnano.org/main.dart.js:4085:43)
    at Object.Design__helices_from_json (https://scadnano.org/main.dart.js:40511:19)
    at Object.Design__helices_and_groups_from_json (https://scadnano.org/main.dart.js:40810:15)
    at Object.Design_from_json (https://scadnano.org/main.dart.js:40888:13)
    at Object.load_dna_file_reducer (https://scadnano.org/main.dart.js:25389:48)
    at StaticClosure.app_state_reducer (https://scadnano.org/main.dart.js:33319:18)
    at Store__createReduceAndNotify_closure.call$1 (https://scadnano.org/main.dart.js:70986:28)
    at StaticClosure.oxdna_export_middleware (https://scadnano.org/main.dart.js:40071:12)
    at Store__createDispatchers_closure.call$1 (https://scadnano.org/main.dart.js:70994:34)
    at StaticClosure.zoom_speed_middleware (https://scadnano.org/main.dart.js:23477:12)

**Comment by LSDaniel2016** [comment]
The question has been sovled by importing .json to there.

**Comment by dave-doty** [comment]
Sorry, I've not had time to get to this yet. Can you say more specifically how it was resolved? I want to make sure there's not still an issue to be fixed here.

**Comment by dave-doty** [comment]
> Sure. I had used "open" to open .json created by cadnano 2 but it didn't work. Yesterday I used "import cadnano v2" and it worked.

Ah, so it sounds like the issue is that the "Open" option should give a more useful error message when the file format is incorrect. Thanks!
