### ISSUE TITLE
crash when adding base pair lines

### ISSUE THREAD

**Issue by alexfarc** [UC-Davis-molecular-computing/scadnano#862]
Bad state: No element

stack trace:
Bad state: No element
    at Object.wrapException (https://scadnano.org/main.dart.js:1257:17)
    at Object.throwExpression (https://scadnano.org/main.dart.js:1271:15)
    at _$Design.find_overlapping_domains_on_helix$1 (https://scadnano.org/main.dart.js:102878:13)
    at _$Design._base_pairs$1 (https://scadnano.org/main.dart.js:102826:36)
    at _$Design.get$base_pairs (https://scadnano.org/main.dart.js:102815:19)
    at _$DesignMainBasePairLinesComponent._create_base_pair_lines_components$0 (https://scadnano.org/main.dart.js:121532:50)
    at _$DesignMainBasePairLinesComponent.render$0 (https://scadnano.org/main.dart.js:121505:45)
    at ReactDartInteropStatics2_handleRender_closure.call$0 (https://scadnano.org/main.dart.js:70914:17)
    at _RootZone.run$1$1 (https://scadnano.org/main.dart.js:48823:18)
    at StaticClosure.ReactDartInteropStatics2_handleRender (https://scadnano.org/main.dart.js:16244:28)

**Comment by dave-doty** [comment]
Can you upload the design you used, and the steps you took to make this error happen?

Thanks,
Dave

**Comment by dave-doty** [comment]
Closing as duplication of #858
